dist: trusty
language: c++
git:
  submodules: false
os:
- linux
- osx
- windows
-
script:
- mkdir build
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/_install
- cmake --build . --target package

deploy:
  provider: releases
  api_key:
    secure: lANavpY1vRcNEpUXFMOJZHyGvcz8PF10zw7qX+nbhaY23UA54ZIWJqHE+VZWOoJBxiXo+jEE1TyacqMwyrL3MDB0B7XJ4tLRtpQpj9NBwvvFPluGiXwhFo8XKeHJZkLYMH6SXHSZ0/07YzRTEQFM38mo5HsiDil6EVWDFyzSspKefb5CuUildu1v7DK+pSPLZgVGnmz33qtMD48REk7/f59G/keyHGklWdOYxPXH3jH1EaFhNZZF5yzpWt+MduHemgrkGNiFd/rigkMmCMt0rPsL9TL9ORpORA103xRSZ1eq6I7xOxmhdPEgG/L+AxUtMX0iOecrA1wRXZVSJlFLfENVACLRe9X9kfNPqJCoNwZQNSVEvKbpyYkDAOLu8qBYbWZAIaAvYHj4eVs/qav2dOzEU6cu6P5tUog+x/48HKjLJezxBVnl0O6aNQSNFjmKjAmOizFmnXNTVegv8b82gPAinEXHuhAkObEqQqmn7LjwAFLP/1fiA1Axn9/pXPuxe6RCsmAWRlF5uMmh9lz7qxfyJNMXysUYwTKVW8Nux5SHj1M+1pC6jUB8OfaO6MS+WHfPxdlc+0yzKdwPpNf7ok4mT0rqNK/ws+GE8f113PzxhhCK0fWcWZiSeMR5iW0xE3ZkVsSMsYsDbkwnUKnqnbMmKSpLYByHmDCyzqTWKww=
  skip_cleanup: 'true'
  file_glob: true
  file: build/native*
  on:
    tags: true
    repo: Cyberunner23/TravisReleasePoC
    branch: master