dist: trusty
language: c++
git:
  submodules: false
os:
- linux
- osx
- windows

script:
- mkdir build
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/_install
- cmake --build . --target package

deploy:
  provider: releases
  api_key:
    secure: aQyRTkisWqIf1A+OIEyhcuDF2RIb1i9W/Y+w4PTfZnCk2lMriUOTMw4vse44FGT9CGOY2i1dZSvJpbeEGCrgXZAIxsRDxRbj2pbWrUEXJU0+aC5LjfE5wvm3dmtuTeK6Wmmx+HtL9MDeUQpuYPLQogB0tPeg4tbZ1ns9iSjw7oK8eOh25XUakVi375/O/prbRCDbK7IP+181adfhh0pKP70jjGwCM06YE4dPmAg4/+t0hxHRZ2Ah3ek6aPVclBTBnlRZtXh+yJBVPufdH6YurqDMHA9EyUfdcvZqYCeoGteLHn43440Cq4czynZ1Yg+jZ1GhKwfE6LsI+FM9TTCHNc9A4kcuMAltAxbTctODGXvFgP+ZaPq27Nsbq92Fges40dBLcFfADEYg/3ryrK9q6XI93T5mV/A4lvDFJhg7PZSiK9ih2gx/0l3Mk7DUVFWtVigQQgIR9i300i4c+0/QpIpqXgYXEvU388y93MEA/1gzDzfrMh3dWx1Bo7naeSw8dSpXY7iD7fT2Zo5kFAJc2yowXYG0eOOO6B9rEnvsn2fDKRDJUHa7Yfl8WdZbtV6cxeMqKjqvqcI5IELJ9lCWX4TQ1J9xZnPerHuRyBYuPpVT1v0Na4oZ8IwHI2npUnMjuM7WOBC5ZIDN6b7+u2hA61hciIdC7NnscSVSF4Bv7mY=
  skip_cleanup: 'true'
  file_glob: true
  file: native*.zip
  on:
    tags: true
    repo: Cyberunner23/TravisReleasePoC
    branch: master