dist: trusty
language: c++
git:
  submodules: false
os:
- linux
- osx
- windows
-
script:
- mkdir build
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/_install
- cmake --build . --target package

deploy:
  provider: releases
  api_key:
    secure: dTFUKDpXYR1FB8DBvbjWLqlUPAJev/lRp8iOmqFxnxp375TWyYsFQ2kBI7Tk8WAhmuq3kkZE0uGp/hHWmy+0CD/OUPUyty+03/nfs8ZMnWSf/Zhu5aUZJfIZdPoHOcPTrCEQ8740+qh/3nQfLyBhK5GzH4FckuFKb88z5dRh6nzhXgULf7zvs6yHoeuwUWmmr+Rk7+m9AAZGIFif0epyP8uVTI34m+oT2yK37E40eJ32ir+k/rq9CgKsvDcVBvij2lvaRQhliRZYnmAONkFkzGNCDz5fnLT5SW721BCXHc5RdLs6JXagGmdJmj6rLwXPD9m2CrZupiX95sqxGYIOoeeJcCujNcowjywN/q1jLMeUmSHAKITJRzk7hOWqFL+SxCylTb/5YMEOsXK3IzHlrZnmgL+qj4a+C68rtRgJj/21bmgXbFuZuiTnDcXJfw2I0tE3XZFe8fURzx+5AQkwbLNps0MldE5oZbziR88/0RpBgnUsj0FohaetZijPeYmhpGg3+gqp4gns5Ffjlg57+uQcxF4dl5IPyriJJe8CYg3Y+E9F1SBJx9mFXM+HjjN+5bRqmdxzRTUXiaathtySIZGan4JMv5joLKjZh0L9YnxxuiHj5o56RnMk9e8ShRYGv6KUVOqld63kXxklaZXsFkLvupdlTZW6ndOq2EdwIjY=
  skip_cleanup: 'true'
  file_glob: true
  file: build/native*
  on:
    tags: true
    repo: Cyberunner23/TravisReleasePoC
    branch: master