sudo: false
dist: trusty

language: c++

git:
  submodules: false

os:
  - linux
  - osx
  - windows

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/_install
  - cmake --build . --target package