dist: trusty
language: c++
git:
  submodules: false
os:
- linux
- osx
- windows
- 
script:
- mkdir build
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/_install
- cmake --build . --target package

deploy:
  provider: releases
  api_key:
    secure: OssWqsdKdiS8vyLulzumkN+8s11+09EiiMGFtAXvowyz1IxXklujxQ4pquyyfCIt6i1vmG4rY8DnkO2lyb7msYzV2Z4udHMJaG0ribg/vEWaXPPafYDbU5QPtLdjWyUuabz92DhBw0IYyvsw+f2HU0at7dd6PkXERBB823WIQl/wk2WKPg0cQKyBiwPv9Knj13YclmZGwdy3g1IQLmIHtg6SEFuRL8wbPkkyvKf6LkDmJh1vBelcp9RmBupiEVu/CtgkwMrS/gLo0dGO7C8Z6dXqCuGg9RnBTiKD6T94ZMoDNw+gGYp2QJdSQkeJCaiX2cC/3KGS+EyIx5d0+3lbmCFlPQjdQNVX4FOJa5eJrLiJNtUeY/ytdQ6K3ZDRlvgjgg20CVJDssCG1psOJN3fez1PfzZLkvC3rzFsuZ0yGf308QuRvdfvorBte2Lv0hCO+D86FQp1gmOUF6a+4UzlgcgFOzm6Gz04NJpWYdhOUFoOCjkMu+L/Lyn2IUlrgAARvxD00Fm/Jr4bLY8+S3eTJOKOsNvGWBUVNa6vDfo31f/ehZWSJ1IJBKQ1rNebtoWF99sDLva8xaMmOLc6NrujUDVVh/X7kgyRsSNM+mCq0WpKD+F4cIw3XYtT6PYVc9WTvtqotc82XwMrjbNN3l8q9rh20Nv1ehAxs0G5TvGM+eo=
  skip_cleanup: 'true'
  file_glob: true
  file: build/native*
  on:
    tags: true
    repo: Cyberunner23/TravisReleasePoC
    branch: master