dist: trusty
language: c++
git:
  submodules: false
os:
- linux
- osx
- windows
-
script:
- mkdir build
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/_install
- cmake --build . --target package

deploy:
  provider: releases
  api_key:
    secure: "hMccrT+1daT1ei7D6thMGAS5wZocxxZAwWieI9MS8YDB1a0veVel5p8BMiG71PJ5v9PM0l0DAt0k6JwoMtHSNgxUgsL6F/CxWrRw32khmeDCDqT6CITyh08Oru/2f8J3JmiK4w6yq+UThd6fLj1Iv4cfclVD0rTM0lIS05h3/bxjsntNsv9uqZNzhSbbvEzilEwilrKQFyOz3sGIoZnx+bmG7SzLNvVxTtvFizdlWAqj/qjZIDTVg7rurUS7eHck14xFV1eJjHxm7ArRNWFrSmX6XHwsUkck3dCdmbYZsLzbiq/khwnA79wtJvneaSZBq5MwMifEDjyuz+vRR5SsWFib3UPV08IYS7E4xvB49NoMfZ82n88EKk1VZT8pK4I5BYZsgwXUKyfPBEcs4eTOH/v7chJQG1QCuI+3txVTGNhuiCZ95wVbkRStKVMPyDA/bY1M+FMnC7riGyv4C2vpiO+NY9D3t10UMu22Bhz/LcahAmzQJndxCjitv52QgUexFwMUJndfgXmcaTfzdbaWpIhZe/ZyfDpT3FWuoSN4bWViCQjJnyt9Sw9iIOnpCDJPFDUe8YA6+VhZjdkAryxt/a+4sdHZpj/V2je5ThC0vykMMQixYWvbv0miqGlorkAJ7xrudrNpdBEIMLpgGj1HTgvG3DwAQDXT7OEhYmzkPn4="
  skip_cleanup: 'true'
  file_glob: true
  file: build/native*
  on:
    tags: true
    repo: Cyberunner23/TravisReleasePoC
    branch: master